name: Apartment Cold Emailed

on:
  workflow_dispatch:
    inputs:
      city:
        description: "City to search (e.g. Evanston IL)"
        required: true
        default: "Evanston IL"
      pages:
        description: "Number of result pages (1–3)"
        required: true
        default: "1"
      write:
        description: "Write results to CSV (true/false)"
        required: false
        default: "false"

permissions:
  contents: read
  actions: none
  id-token: write

jobs:
  scrape:
    if: github.actor == 'mikedafi'
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python cli.py \
            --city "${{ github.event.inputs.city }}" \
            --pages ${{ github.event.inputs.pages }} \
            ${{ github.event.inputs.write == 'true' && '--write' || '' }}